#!/bin/bash
#
# description: Bash file to manage NPM Installs
# author: Peter Schmalfeldt <peter@redvanworkshop.com>

# Change to Project Root
BASE='/workspaces/sfcc-vscode-remote'

APP_NAME="SFCC REMOTE"

# Supress Node Warnings Globally
export NODE_NO_WARNINGS=1

make_header(){
    TEXT=$( echo $1 | tr '\n' ' ')
    echo -e "\n\033[48;5;22m  $APP_NAME › $TEXT  \033[0m"
}

output(){
    TEXT=$( echo $1 | tr '\n' ' ')
    echo -e "\n\033[7m › \033[27m $TEXT"
}

error(){
    TEXT=$( echo $1 | tr '\n' ' ')
    echo -e "\n\033[38;5;196m× $TEXT\033[0m\n"
}

success(){
    TEXT=$( echo $1 | tr '\n' ' ')
    echo -e "\n\033[38;5;34m✓ $TEXT\033[0m\n"
}

notice(){
    TEXT=$( echo $1 | tr '\n' ' ')
    echo -e "\033[38;5;220m→ $TEXT\033[0m\n"
}

confirm(){
    echo -ne "\n\033[38;5;220m⚠ $1\033[0m"
}

make_header "CLEAN INSTALL"

# Make sure we are in the root of the project
if test -f "$BASE/dw.json"; then
  # Check if we want to remove existing node modules folders
  confirm "Remove node_modules folders? (y or n): "
  read CONFIRM
  case $CONFIRM in
    y|Y|YES|yes|Yes)
      output "Removing existing node_modules folders ..."
      find $BASE -name 'node_modules' -type d -prune -exec rm -rf '{}' +
    ;;
    n|N|no|NO|No)
    ;;
    *)
      notice "Please enter only y or n"
  esac

  # Check if we want to reset NPM Cache
  confirm "Clean NPM Cache? (y or n): "
  read CONFIRM
  case $CONFIRM in
    y|Y|YES|yes|Yes)
      output "Cleaning NPM Cache ..."
      npm cache clean --force --loglevel error
    ;;
    n|N|no|NO|No)
    ;;
    *)
    notice "Please enter only y or n"
  esac

  # Install NPM Packages in Workspace Root
  if test -f "$BASE/package.json"; then
    output "Installing Base NPM Packages"
    npm install --no-optional --loglevel error --no-audit
  else
    error "Missing package.json"
  fi

  success "ALL DONE"
else
  error "Missing dw.json ( are you in the right directory? )"
fi
