#!/usr/bin/env bash
#
# description: Bash file to perform a Clean Install of Project
# author: Peter Schmalfeldt <peter@redvanworkshop.com>

# Import Common Functions and Constants
source /usr/local/lib/sfcc-remote/common

make_header "CLEAN INSTALL"

# Make sure we are in the root of the project
if test -f "$PROJECT_BASE/dw.json"; then
  # Check if we want to remove existing node modules folders
  confirm "Remove node_modules folders? ( Y or N ): "
  read CONFIRM
  case $CONFIRM in
    y|Y|YES|yes|Yes)
      output "Removing existing node_modules folders ..."
      find $PROJECT_BASE -name 'node_modules' -type d -prune -exec rm -rf '{}' +
    ;;
    n|N|no|NO|No)
    ;;
    *)
      notice "Please enter only Y or N"
  esac

  # Check if we want to reset NPM Cache
  confirm "Clean NPM Cache? ( Y or N ): "
  read CONFIRM
  case $CONFIRM in
    y|Y|YES|yes|Yes)
      output "Cleaning NPM Cache ..."
      npm cache clean --force --loglevel error
    ;;
    n|N|no|NO|No)
    ;;
    *)
    notice "Please enter only Y or N"
  esac

  # Install NPM Packages in Workspace Root
  if test -f "$PROJECT_BASE/package.json"; then
    output "Installing Base NPM Packages"
    npm install --no-optional --loglevel error --no-audit
  else
    error "Missing package.json"
  fi

  # ==================================================
  # PUT YOUR DEV TEAMS CUSTOM INSTALLER CODE BELOW
  # ==================================================

  success "ALL DONE"
else
  error "Missing dw.json ( are you in the right directory? )"
fi
